### ISSUE TITLE
install requires tensorflow

### ISSUE THREAD

**Issue by oriolnfe** [adpauna/qrassh#1]
Hello,

I have tried installing and running qrassh. The installation, following the steps worked correctly, but when running the honeypot, twisted requires tensorflow through Keras. 

exceptions.ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

I have tried forcing several versions of Keras and Tensorflow without success. Could you share if there were any additional installation steps for you?

**Comment by oriolnfe** [comment]
solved by downgrading to Keras 2.15 and Tensorflow 1.6 with pip

**Comment by louisshiru** [comment]
> solved by downgrading to Keras 2.15 and Tensorflow 1.6 with pip

Could you share your setup steps and environment? I think keras 2.15 only works with python3

**Comment by oriolnfe** [comment]
I was bound to using python2 :(
